[package]
name = "viren"
version = "0.1.0"
edition = "2021"

[dependencies]
json = "0.12.4"
rand = "0.3"
regex = "0.2"
reqwest = "0.12.11"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde ="1.0"
serde_derive="1.0"
